name: mybatis-mapper-demo
path: /home/app/code/svn/UIV1/branches/active-standby/cz-cloud/model-base
templates: template
author: hujh
version: v1.0

database:
  dialect: MYSQL
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://192.168.24.74:3306/scloud?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
  user: root
  password: Pwdis123

entity:
  enable: true
  pkg: cn.com.nexwise.cloudadmin.pojo

dao:
  enable: true
  baseMapper: cn.com.nexwise.mybatis.CloudMapper
  pkg: cn.com.nexwise.cloudadmin.dao

xml:
  enable: true
  pkg: mappers.cn.com.nexwise.cloudadmin.mapper

example:
  enable: true
  pkg: cn.com.nexwise.cloudadmin.pojo

conf:
  enable: true
  pkg: cn.com.nexwise.cloudadmin.pojo

tables:
  - name: %